# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculador.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(692, 464)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 50, 341, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 180, 90, 30))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 240, 90, 30))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 300, 90, 30))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txtNota1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNota1.setGeometry(QtCore.QRect(150, 170, 111, 41))
        self.txtNota1.setObjectName("txtNota1")
        self.txtNota2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNota2.setGeometry(QtCore.QRect(150, 230, 111, 41))
        self.txtNota2.setObjectName("txtNota2")
        self.txtNota3 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNota3.setGeometry(QtCore.QRect(150, 290, 111, 41))
        self.txtNota3.setObjectName("txtNota3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(340, 130, 111, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.txtResultado = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtResultado.setGeometry(QtCore.QRect(340, 170, 251, 171))
        self.txtResultado.setObjectName("txtResultado")
        self.btnCalcular = QtWidgets.QPushButton(self.centralwidget)
        self.btnCalcular.setGeometry(QtCore.QRect(160, 350, 90, 40))
        self.btnCalcular.setObjectName("btnCalcular")
        self.btnNuevo = QtWidgets.QPushButton(self.centralwidget)
        self.btnNuevo.setGeometry(QtCore.QRect(340, 360, 90, 40))
        self.btnNuevo.setObjectName("btnNuevo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 692, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Calculador de Promedios"))
        self.label_2.setText(_translate("MainWindow", "Nota 1:"))
        self.label_3.setText(_translate("MainWindow", "Nota 2:"))
        self.label_4.setText(_translate("MainWindow", "Nota 3:"))
        self.label_5.setText(_translate("MainWindow", "Condicion"))
        self.btnCalcular.setText(_translate("MainWindow", "Calcular"))
        self.btnNuevo.setText(_translate("MainWindow", "Nuevo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
