# Form implementation generated from reading ui file 'triangulo.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 254, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 50, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 130, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 130, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(220, 130, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txtA = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtA.setGeometry(QtCore.QRect(70, 190, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtA.setFont(font)
        self.txtA.setObjectName("txtA")
        self.txtB = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtB.setGeometry(QtCore.QRect(220, 190, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtB.setFont(font)
        self.txtB.setObjectName("txtB")
        self.txtC = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtC.setGeometry(QtCore.QRect(370, 190, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtC.setFont(font)
        self.txtC.setObjectName("txtC")
        self.btnProcesar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnProcesar.setGeometry(QtCore.QRect(600, 140, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnProcesar.setFont(font)
        self.btnProcesar.setObjectName("btnProcesar")
        self.btnNuevo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnNuevo.setGeometry(QtCore.QRect(600, 200, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnNuevo.setFont(font)
        self.btnNuevo.setObjectName("btnNuevo")
        self.txtR = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.txtR.setGeometry(QtCore.QRect(70, 300, 621, 111))
        self.txtR.setObjectName("txtR")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">TRIÁNGULO</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "LADO A:"))
        self.label_3.setText(_translate("MainWindow", "LADO C:"))
        self.label_4.setText(_translate("MainWindow", "LADO B:"))
        self.btnProcesar.setText(_translate("MainWindow", "Procesar"))
        self.btnNuevo.setText(_translate("MainWindow", "Nuevo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
